"""add payment_provider to orders

Revision ID: 39190f687338
Revises: 2f74e7fae96d
Create Date: 2026-08-04 18:23:05.725014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39190f687338'
down_revision: Union[str, Sequence[str], None] = '2f74e7fae96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('category', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('variant', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_provider', sa.String(), nullable=True))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='paymentstatus', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='paymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('orders', 'payment_provider')
    op.drop_column('order_items', 'sku')
    op.drop_column('order_items', 'variant')
    op.drop_column('order_items', 'category')
    # ### end Alembic commands ###
